# ---------------------------------------------------- #
#                  Spawn by rockquiet                  #
# ---------------------------------------------------- #
#    Wiki - https://github.com/rockquiet/Spawn/wiki    #
# ---------------------------------------------------- #

options:
  # toggle if the player receives fall damage on teleport
  fall-damage: false
  # toggle if the player should be teleported to spawn on join
  teleport-on-join: false
  # toggle if the player should be teleported to spawn only on first join
  teleport-on-first-join: false
  #
  # TELEPORT COOLDOWN
  # how long in SECONDS the player has to wait before teleporting to spawn again
  # to disable cooldown set it to: 0
  teleport-cooldown: 10
  #
  # TELEPORT DELAY
  # the delay in SECONDS until the player gets teleported to spawn
  # to disable cooldown set it to: 0
  teleport-delay: 3
  # toggle if the teleport should be canceled if the player moves
  cancel-on-move: true
  #
  # VOID TELEPORT
  # toggle if the player should be teleported to spawn if falling in void
  teleport-out-of-void: false
  # the height at which the player gets teleported out of the void to spawn
  # Minecraft playable Altitude: -64 -> 320 [integer]
  void-check-height: -64
  #
  # DEATH TELEPORT
  # toggle if the player should be teleported to spawn if they die
  teleport-on-respawn: false
  # toggle if the bed spawn-point should be ignored
  ignore-bed-spawn: false
  #
  # PARTICLES
  # spawns particles on teleport
  # all particles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  # use these for 1.8: https://hub.spigotmc.org/nexus/service/local/repositories/snapshots/archive/org/spigotmc/spigot-api/1.8.8-R0.1-SNAPSHOT/spigot-api-1.8.8-R0.1-20160221.082514-43-javadoc.jar/!/org/bukkit/Effect.html
  particle: PORTAL
  # the number of particles which get used
  # to disable particles set it to: -1
  particle-amount: 40
  #
  # SOUNDS
  # plays a sound on teleport
  # sounds for Minecraft 1.8 - 1.19: https://www.andre601.ch/Spigot-Sounds/sounds/
  sound: ENTITY_ENDERMAN_TELEPORT
  # the volume of the sound
  # to disable sounds set it to: 0.0
  sound-volume: 1.0
  # the pitch of the sound
  sound-pitch: 1.0
#
# basic formatting with '&' codes is supported
# to disable a message set it to: ''
messages:
  # successful teleport to spawn
  teleport: '&aTeleported to Spawn'
  # successfully teleported another player to spawn - /spawn %player%
  teleport-other: '&aSuccessfully teleported &2%player% &ato Spawn'
  # if the player to be teleported is offline - /spawn %player%
  player-not-found: '&cPlayer &4%player% &cnot found!'
  #
  # if the player still has an active teleport cooldown
  cooldown-left: '&cPlease wait &4%cooldown% &csecond(s) before teleporting again.'
  #
  # time left until the player gets teleported to spawn
  delay-left: '&6You will be teleported in &e%delay% &6second(s).'
  # delayed teleport failed because the player moved
  teleport-canceled: '&cTeleport canceled because you moved!'
  #
  # spawn set at current position
  spawn-set: '&aSpawn set successfully'
  #
  # config reloaded
  config-reload: '&aConfig reloaded successfully'
  #
  # no spawn set in config - set one with /spawn set
  no-spawn: '&cNo Spawn is set!'
  # no permissions for command
  no-permission: '&cNo permissions!'
  # command cannot be used in console
  no-player: '&cCommand can only be used by players!'
#
# Location data of Spawn
# only edit if you know what you are doing
spawn: {}
